name = "DiffPointRasterisation"
uuid = "f984992d-3c45-4382-99a1-cf20f5c47c61"
authors = ["Wolfhart Feldmeier <wolfhart.feldmeier@uni-jena.de>"]
version = "1.0.0-DEV"

[deps]
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
